# Generated by Django 5.1.4 on 2025-01-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='type',
            field=models.CharField(blank=True, choices=[('driver', 'Driver'), ('midrange', 'Midrange'), ('putter', 'Putter'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
