# Generated by Django 5.1.4 on 2025-01-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0003_manufacturer_disc_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='mold_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
