# Generated by Django 5.1.4 on 2025-01-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0005_disc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disc_images/'),
        ),
    ]
