# Generated by Django 5.1.4 on 2025-01-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0006_disc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='type',
            field=models.CharField(blank=True, choices=[('Driver', 'Driver'), ('Midrange', 'Midrange'), ('Putter', 'Putter'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
