# Generated by Django 5.1.4 on 2025-01-13 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0007_alter_disc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='disc.disc')),
                ('lost_disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='disc.disc')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('lost_disc', 'found_disc')},
            },
        ),
    ]
