# Generated by Django 5.1.4 on 2025-03-25 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0008_discmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='disc.disc')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
