# Generated by Django 5.1.4 on 2025-03-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0010_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
