# Generated by Django 5.1.4 on 2025-03-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0012_alter_disc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='disc',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=10),
        ),
    ]
