# Generated by Django 5.1.4 on 2025-03-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0013_disc_state_alter_disc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('black', 'Black'), ('brown', 'Brown'), ('gray', 'Gray'), ('white', 'White'), ('multi', 'Multi'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disc',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='disc',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
